name: listing, testing, building
on: 
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
    
    steps:
      - uses: actions/checkout@v4.2.0
      - name: Staring Node.js ${{ matrix.node-version}} 
        uses: actions/setup-node@v3.8.2
        with:
          node-version: ${{ matrix.node-version}} 
      - name: install modules
        run: npm install --legacy-peer-deps
      - name: Build Typescript Files
        run: npm run build:ts
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
