name: listing, testing, building
on: 
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
    
    steps:
      - uses: actions/checkout@v4.2.0
      - name: Staring Node.js ${{ matrix.node-version}} 
        uses: actions/setup-node@v3.8.2
        with:
          node-version: ${{ matrix.node-version}} 
      - name: install modules
        run: npm ci --legacy-peer-deps
      - name: Compile TypeScript (including config)
        run: npx tsc --esModuleInterop --module commonjs --target es5 webpack.config.ts config/build/**/*.ts
      - name: build production project
        run: webpack --env mode=production
      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
